# Generated by Django 3.2.8 on 2022-02-15 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
