# Generated by Django 3.2.8 on 2022-02-15 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
