# Generated by Django 3.2.8 on 2022-02-15 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product_db',
        ),
    ]
